import { bluRay, book, cinemaMovie } from '../../app/shelf';

export default [
  bluRay({
    title: '12th fail',
    yearOfRelease: '2023',
    imdbId: 'tt23849204',
    coverPath: '/content/shelf/12th-fail.jpg',
    rating: 8,
    watchedOn: '2026-05-14',
    worthWatching: true,
  }),
  book({
    title: 'Black Ember',
    author: 'Helia James',
    isbn13: '9783769311587',
    coverPath: '/content/shelf/black-ember.jpeg',
    reading: true,
    nsfw: true,
    worthReading: true,
  }),
  book({
    title: 'Handbook of Usability Testing',
    author: 'Jeffrey Rubin, Dana Chisnell',
    isbn13: '9780470185483',
    coverPath: '/content/shelf/handbook-of-usability-testing.jpeg',
    reading: true,
    worthReading: true,
  }),
  bluRay({
    title: 'Flow',
    yearOfRelease: '2024',
    imdbId: 'tt4772188',
    coverPath: '/content/shelf/flow.jpg',
    rating: 8,
    watchedOn: '2026-04-23',
    worthWatching: true,
  }),
  bluRay({
    title: 'Wolfwalkers',
    yearOfRelease: '2020',
    imdbId: 'tt5198068',
    coverPath: '/content/shelf/wolfwalkers.jpg',
    rating: 8.5,
    watchedOn: '2026-04-16',
    worthWatching: true,
  }),
  cinemaMovie({
    title: 'Project Hail Mary',
    yearOfRelease: '2026',
    imdbId: 'tt12042730',
    coverPath: '/content/shelf/project-hail-mary.svg',
    rating: 9,
    watchedOn: '2026-04-09',
    worthWatching: true,
  }),
  cinemaMovie({
    title: 'Iron Lung',
    yearOfRelease: '2026',
    imdbId: 'tt27564844',
    coverPath: '/content/shelf/iron-lung.svg',
    rating: 7,
    watchedOn: '2026-02-07',
    worthWatching: true,
    review: `I liked it, it was quite a weird experience. Only worth it if you have know the game or jacksepticeye.`,
  }),
];
